name: CI

'on':
    push:
        branches:
            - main
    pull_request: null
    schedule:
        -
            cron: '0 0 * * MON'

jobs:
    check-python-cs:
        name: Check Python CS
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./back

        steps:
            -
                uses: actions/checkout@v3
            -
                uses: actions/setup-python@v4
                with:
                    python-version: '3.x'
            -
                run: 'pip install pycodestyle'
            -
                run: 'pycodestyle --ignore=E501,W605,E722 invoke.py tasks.py'
    ci:
        defaults:
            run:
                working-directory: ./back

        name: Test with PHP ${{ matrix.php-version }}
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.1', '8.2']

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            -
                uses: actions/setup-python@v4
                with:
                    python-version: '3.9'
            -
                run: 'pip3 install pipenv'

            -   name: Set PHP version
                run: sed -i "s/^php_version = .*/php_version = '${{ matrix.php-version }}'/" invoke.py

            -
                run: 'pipenv install --deploy --dev'
            -
                run: 'pipenv run inv start && sleep 5'
            -
                name: 'Test the infrastructure is working'
                run: |
                    set -e
                    set -o pipefail
                    curl --fail --insecure --silent -H "Host: app.test" https://127.0.0.1 | grep "Hello world"
                    curl --fail --insecure --silent -H "Host: app.test" https://127.0.0.1 | grep "${{ matrix.php-version }}"

            - name: Setup PHP ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                php-version: '${{ matrix.php-version }}'

            # - name: Run the tests
            #   run: make test

            # - name: Check CS
            #   run: make cs_dry_run

            # - name: Run PHPStan
            #   run: make phpstan
